### ISSUE TITLE
groestlcoinj-core

### ISSUE THREAD

**Issue by magnearun** [Groestlcoin-Archives/groestlcoin-wallet-old#2]
I ´m not able to find groestlcoinj-core in maven central.

```
<!-- com.google.bitcoin.* -->
    <dependency>
        <groupId>org.bitcoinj</groupId>
        <artifactId>groestlcoinj-core</artifactId>
        <version>0.12.2</version>
    </dependency>
```

When I try to build the wallet I get the following error: 
"Non-resolvable parent POM: Could not find artifact org.bitcoinj:groestlcoin-parent:pom:0.12.2 in central (http://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM"

**Comment by HashEngineering** [comment]
It is not in maven, but it is available in the groestlcoinj repo in this
same account.
